name: smk_edu_management_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  rename_app: ^1.6.2
  vector_graphics: ^1.1.18
  gap: ^3.0.1
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/vector/

flutter_native_splash:
  color: "#111B26"
  image: assets/images/splash_skema_logo.png
  android_12:
    color: "#111B26"
    image: assets/images/splash_logo_android12.png
